- hosts: all 
  remote_user: ec2-user
  become: yes
  tasks:
     - name: To install apache
       yum:
            name: httpd
            state: present
     - name: To Start apache
       service:
            name: httpd
            state: started
     - name: To copy the file
       copy: 
              src: ./index.html
              dest: /var/www/html/index.html

